### PR TITLE
[Feature] Export Shopify const as an alias to use with ES modules

### PR DESCRIPTION
**Pull request by stefanosala**
### WHY are these changes introduced?

When using this lib in a ES module context (e.g. Node v15) you need to use the lib like this:

```javascript
import Shopify from '@shopify/shopify-api';

await Shopify.default.Clients.Rest(...);
```

With this change you can just import the `Shopify` variable directly:

```javascript
import { Shopify } from '@shopify/shopify-api';

await Shopify.Clients.Rest(...);
```

## Type of change

- [ ] Patch: Bug (non-breaking change which fixes an issue)
- [x] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have added a changelog entry, prefixed by the type of change noted above
- [ ] I have added/updated tests for this change
- [ ] I have documented new APIs/updated the documentation for modified APIs (for public APIs)

### CODE REVIEW

**Comment by stefanosala** [comment]
I'm honestly not sure if this is the right way of doing this, sorry! :)

**Comment by paulomarg** [comment]
Hey @stefanosala, thank you for contributing! I think your change makes sense, I don't see any problems with it.

However, could you please clone the original repo, and create a PR from a branch in there? That will run our CI checks to make sure everything is in order before we merge your changes!

**Comment by stefanosala** [comment]
@paulomarg I'm not sure I can push a branch on your original repo?

**Comment by paulomarg** [comment]
Right @stefanosala, sorry about that! We've tweaked the checks so that they run on forks, could you please re-create this PR so we can run them?

**Comment by stefanosala** [comment]
It should be all done in this pr :)

**Review by paulomarg — APPROVED** [review]

**Comment by paulomarg** [comment]
Merged, thanks for bearing with us @stefanosala!

**Pull request merged**
