### PR TITLE
Bump jest to v27.4.3

### PR DESCRIPTION
**Pull request by paulomarg**
This PR bumps the `jest` dependency to the latest version under v26.

### CODE REVIEW

**Comment by JaKXz** [comment]
Curious why we can't move to v27?

**Comment by paulomarg** [comment]
Oh great point, we most likely can, I just ran the wrong command 😅 .

**Comment by paulomarg** [comment]
Upgraded it to v27 instead, tests still happily work.

**Review by JaKXz — APPROVED** [review]
🔥

**Pull request merged**
